BOX-250: add isSaved field for card dto
cardboxdev/backend pull request #57
Opened 2021-10-27 16:32 UTC by azinit

2021-10-27 16:35 UTC, azinit reviewed
self-reviewed

2021-10-27 22:03 UTC, sergeysova approved these changes

2021-11-23 08:46 UTC, sergeysova requested changes

2021-11-23 08:46 UTC, sergeysova commented on api-internal/openapi.yaml
> +      required: [id, content, title, createdAt, updatedAt, authorId, tags, isSaved]
```suggestion
      required: [id, content, title, createdAt, updatedAt, authorId, tags, meta]
```

2022-01-16 09:56 UTC, sergeysova approved these changes

2022-01-16 09:56 UTC, merged

2022-01-16 09:56 UTC, sergeysova commented
@azinit Спасибо! ❤️